#!/bin/bash

### WARNING: this was generated by an LLM!!! I don't know bash nor do I want to
### torture myself!!!

show_help() {
    echo "Usage: dev.sh <subcommand> [options]"
    echo "Subcommands:"
    echo "  w, watch [options] <file.cr> [args...] : Watch and run the Crystal file"
    echo "    Options:"
    echo "      -l <log level> : Set the LOG_LEVEL environment variable"
    echo "  s, soma [options] : Run the soma6.cr file"
    echo "    Options:"
    echo "      -r, --release : Build with --release flag"
    echo "  t, test [args...] : Run the pattern6_test.cr file with additional arguments"
    echo "  i, init : Install shards and build the crsfml library"
}

if [ $# -eq 0 ]; then
    show_help
    exit 1
fi

subcommand=$1
shift

case $subcommand in
    w|watch)
        # Parse arguments for w/watch
        log_level=""
        file=""
        additional_args=()
        while [ $# -gt 0 ]; do
            case $1 in
                -l)
                    shift
                    if [ $# -eq 0 ]; then
                        echo "Error: -l requires an argument"
                        exit 1
                    fi
                    log_level=$1
                    ;;
                *)
                    if [ -z "$file" ]; then
                        file=$1
                    else
                        additional_args+=("$1")
                    fi
                    ;;
            esac
            shift
        done
        if [ -z "$file" ]; then
            echo "Error: Missing file path"
            show_help
            exit 1
        fi
        # Construct the command
        if [ -n "$log_level" ]; then
            env_var="LOG_LEVEL=$log_level"
        else
            env_var=""
        fi
        watchexec -r --stop-signal SIGINT -w "$file" -- $env_var crystal run "$file" --progress -Dpreview_mt --error-trace -Dexecution_context -- "${additional_args[@]}"
        ;;
    s|soma)
        # Parse arguments for s/soma
        release=false
        while [ $# -gt 0 ]; do
            case $1 in
                -r|--release)
                    release=true
                    ;;
                *)
                    echo "Error: Unexpected argument '$1' for soma subcommand"
                    show_help
                    exit 1
                    ;;
            esac
            shift
        done
        # Construct the command
        if $release; then
            release_prefix="build -o soma --release"
        else
            release_prefix="run"
        fi
        current_dir=$(pwd)
        link_flags="-L${current_dir}/ext/sfml/lib"
        crystal $release_prefix soma6.cr -Dpreview_mt --progress --error-trace -Dsoma6 -Dexecution_context --link-flags "$link_flags"
        ;;
    t|test)
        # Parse arguments for t/test
        additional_args=()
        while [ $# -gt 0 ]; do
            additional_args+=("$1")
            shift
        done
        # Construct the command
        crystal run pattern6_test.cr --progress -Dpreview_mt -Dexecution_context --error-trace -- "${additional_args[@]}"
        ;;
    i|init)
        # Run shards install
        shards install
        # Go to lib/crsfml and run make clean and make with SFML include dir
        cd lib/crsfml || { echo "Error: Directory lib/crsfml not found"; exit 1; }
        make clean
        current_dir=$(pwd)
        sfml_include_dir="${current_dir}/../../ext/sfml/include"
        make SFML_INCLUDE_DIR="$sfml_include_dir"
        cd - || exit 1
        ;;
    *)
        echo "Error: Unknown subcommand '$subcommand'"
        show_help
        exit 1
        ;;
esac
