module Ww::D7
  # This is usually generated by `D7.case`. `QueryIR` is later transformed to
  # `Regime::Query` which is much less pleasant to construct by hand.
  defrecord QueryIR,
    name : Term,
    pattern : Term,
    deps : Slice({Regime::Link, DepIR})

  struct QueryIR
    # Parses *term*, which should be a valid query DSL expression. Raises
    # `ArgumentError` if *term* is malformed.
    #
    # See `D7.case` for DSL docs.
    def self.parse(term : Term) : QueryIR
      Term.matchp(term, <<-WWML) do |query, name, deps|
      (query_ name_
       (%many deps_ min: 0
         -> link_ pattern_ {¦ name_
                              min_: (%optional 1 (%number +i32))
                              max_: (%optional 1 (%any° ∞ (%number +i32)))}))
      WWML
        dep_irs = deps.items.to_readonly_slice do |dep|
          link = Term.case(dep[:link]) do
            matchpi %{(one capture_)} do
              Regime::LinkOne.new(capture)
            end

            matchpi %{(many capture_ dep-capture_)} do
              Regime::LinkMany.new(capture, dep_capture)
            end
          end

          min = dep[:min].to(Int32)
          max = dep[:max] == Term.of(:∞) ? Int32::MAX : dep[:max].to(Int32)

          {link, DepIR.new(dep[:name], dep[:pattern], min, max)}
        end

        QueryIR.new(name, query, dep_irs)
      end
    end
  end

  # See `QueryIR`.
  defrecord DepIR,
    name : Term,
    pattern : Term,
    min : Int32,
    max : Int32

  class Regime
    alias PatternId = UInt32

    defcase Query,
      index : Int32,
      name : Term,
      pattern_id : PatternId,
      specificity : M1::Specificity,
      deps : Slice({Link, Dep})

    defrecord Dep,
      name : Term,
      pattern_id : PatternId,
      head : Term,
      min : Int32,
      max : Int32

    alias Link = LinkOne | LinkMany

    defrecord LinkOne, capture : Term
    defrecord LinkMany, capture : Term, dep_capture : Term

    defrecord Pattern, op : M1::Op::Any

    # :nodoc:
    def initialize(@patterns : Slice(Pattern), @queries : Hash(Term, Array(Query)))
    end

    # Constructs a regime from the given list of query IR objects.
    def self.new(query_irs : Indexable(QueryIR)) : Regime
      patterns = Pf::Kit.stack_array(Pattern)

      queries = {} of Term => Array(Query)

      query_irs.each_with_index do |query_ir, index|
        query_pattern_id = patterns.size.to_u32
        query_normp = M1.normal(query_ir.pattern)
        query_pattern = M1.operator(query_normp)
        query_specificity = M1.specificity(query_normp)
        query_head = M1.head?(query_normp)
        assert query_head, "Could not determine query pattern's head: #{query_ir.pattern}"

        patterns << Pattern.new(query_pattern)

        deps = query_ir.deps.to_readonly_slice do |(link, dep_ir)|
          dep_pattern_id = patterns.size.to_u32
          dep_normp = M1.normal(dep_ir.pattern)
          dep_pattern = M1.operator(dep_normp)
          dep_head = M1.head?(dep_normp)
          assert dep_head, "Could not determine query dependency's head: #{dep_ir.pattern}"

          patterns << Pattern.new(dep_pattern)

          {link, Dep.new(dep_ir.name, dep_pattern_id, dep_head, dep_ir.min, dep_ir.max)}
        end

        bucket = queries.put_if_absent(query_head) { [] of Query }
        bucket << Query.new(index, query_ir.name, query_pattern_id, query_specificity, deps)
      end

      new(patterns.to_readonly_slice(&.itself), queries)
    end

    private def match?(pattern_id : PatternId, candidate : Node) : Term::Dict?
      pattern = @patterns[pattern_id]
      return unless M1.probably_matches?(pattern.op, candidate.term)

      M1.match?(Term[], pattern.op, candidate.term)
    end

    private def crawl(hg, node : Node, query : Query, &fn : MatchTable ->)
      return unless query_env = match?(query.pattern_id, node)

      seen = Pf::USet32[node.id]
      responses = [] of MatchGroup | Slice(MatchGroup)

      query.deps.each do |link, dep|
        case link
        in LinkOne
          unless link_edge = query_env[link.capture]?
            raise KeyError.new("capture `#{link.capture}` not found")
          end

          {% unless flag?(:release) %}
            assert Term.edge?(link_edge)
          {% end %}

          matches = Pf::Kit.stack_array(Match)

          link_edge_abs = hg.abs_edge(link_edge, wrt: node.id)

          hg.each_neighbor(of: node.id, on: link_edge_abs) do |neighbor|
            next if neighbor.id.in?(seen) # Don't allow to depend on the same node twice.
            next unless dep_env = match?(dep.pattern_id, neighbor)

            # Since dep patterns are detached from the query pattern, we can't rely
            # on M1 constraints and must instead provide an environment to relate
            # everything manually. Here, e.g., for @a:
            #
            # (qux @⏏a_⏏ @b_) foo
            #   -> (one ⏏a⏏) (cell @⏏a_⏏ x_) {name: bar}
            #   -> (one b) (cell @b_ y_) {name: baz}
            #
            # We must also compare by *absolute* edges, meaning edges with scope info,
            # rather than simply by names with whatever was captured. This handles
            # more "obscure" edge cases such as the one shown here:
            #
            #  (cell @a)
            #  (module {@b: @a}
            #    (cell @a 100)
            #    (feed @a @b))
            #
            # Notice how both cells have the same name. If we do not "normalize" both
            # wrt. their scope, we'd think of them as the same cell, which leads to
            # invalid behavior.
            dep_edge = dep_env[link.capture]
            dep_edge_abs = hg.abs_edge(dep_edge, wrt: neighbor.id)
            next unless link_edge_abs == dep_edge_abs

            seen = seen.add(neighbor.id)
            matches << Match.new(neighbor, dep_env)
          end

          responses << matches.to_readonly_slice(&.itself)
        in LinkMany
          unless link_edges = query_env[link.capture]?
            raise KeyError.new("capture `#{link.capture}` not found")
          end

          {% unless flag?(:release) %}
            assert link_edges.items.all? { |edge| Term.edge?(edge) }
          {% end %}

          response = link_edges.items.to_readonly_slice do |link_edge|
            matches = Pf::Kit.stack_array(Match)

            link_edge_abs = hg.abs_edge(link_edge, wrt: node.id)

            hg.each_neighbor(of: node.id, on: link_edge_abs) do |neighbor|
              next if neighbor.id.in?(seen) # Don't allow to depend on the same node twice.
              next unless dep_env = match?(dep.pattern_id, neighbor)

              dep_edge = dep_env[link.dep_capture]
              dep_edge_abs = hg.abs_edge(dep_edge, wrt: neighbor.id)
              next unless link_edge_abs == dep_edge_abs

              seen = seen.add(neighbor.id)
              matches << Match.new(neighbor, dep_env)
            end

            matches.to_readonly_slice(&.itself)
          end

          responses << response
        end
      end

      # Enforce agreement: make sure that edges in dependencies agree with
      # the query env. For example, in:
      #
      #   (qux @a_ @b_ @c_) qux
      #     -> (one a) (foo @a_ ⏏@b_⏏) {name: foo}
      #     -> (one b) (bar @b_ ⏏@c_⏏) {name: bar}
      #     -> (one c) (baz @c_ ⏏@a_⏏) {name: baz}
      #
      # ... the highlighted edges must be in agreement with the query env.
      #
      # We do not enforce agreement among dependencies *for captures absent in
      # the master env*. For example, in:
      #
      #   (qux @a_ @b_) qux
      #     -> (one a) (foo @a_ term_) {name: foo}
      #     -> (one b) (bar @b_ term_) {name: bar}
      #
      # ... both *term*s are matched independently.
      responses.map! do |response|
        case response
        in MatchGroup
          D7.select(response, &.env.agrees_with?(query_env))
        in Slice(MatchGroup) # children
          response.map do |child|
            D7.select(child, &.env.agrees_with?(query_env))
          end
        end
      end

      match_table = MatchTable.assoc(query.name, MatchGroup[Match.new(node, query_env)])

      # Make sure dependency bounds are satisfied after agreement.
      query.deps.zip(responses) do |(_, dep), response|
        case response
        in MatchGroup
          return unless dep.min <= D7.degree(response) <= dep.max
        in Slice(MatchGroup)
          # All of groups must satisfy dep's bound.
          return unless response.all? { |group| dep.min <= D7.degree(group) <= dep.max }

          # Now that we've checked their bounds we can merge them into one
          # big group.
          response = Slice.join(response)
          assert response.is_a?(MatchGroup)
        end

        match_table = match_table.assoc(dep.name, response)
      end

      fn.call(match_table)
    end

    # :nodoc:
    #
    # Represents a solution.
    defcase Soln, match_table : MatchTable, query : Query, query_index : Int32 do
      @degree = Int32::MAX

      def degree : Int32
        if @degree == Int32::MAX
          @degree = D7.degree(match_table)
        end

        assert 0 <= @degree < Int32::MAX

        @degree
      end

      @participants : Slice(Term)?

      def participants : Slice(Term)
        @participants ||= begin
          participants = Pf::Kit.stack_array(Term, 8)

          D7.each_match(match_table) do |match|
            participants << match.node.term
          end

          participants.sort! { |a, b| Term.compare(a, b) }
          participants.to_readonly_slice(&.itself)
        end
      end

      # NOTE: the smallest rank is the most specific rank, it should be picked
      # the earliest.
      def <=>(other : Soln) : Int32
        # Prefer higher degree.
        cmp = other.degree <=> degree
        return cmp unless cmp == 0 # equal

        # Prefer higher query specificity.
        cmp = other.query.specificity <=> query.specificity
        assert cmp, "NaNs found in specificity"
        return cmp unless cmp == 0 # equal

        # Prefer solutions for rules lower down (programmers usually read "X
        # below Y" as "X overrides Y").
        cmp = query_index <=> other.query_index
        return cmp unless cmp == 0 # equal

        # Prefer lexicographically smallest solutions.
        participants <=> other.participants
      end
    end

    private def compatible?(a : Tpath, b : Tpath) : Bool
      if a.size == b.size
        return a != b # if different, then they're compatible
      end

      sm, lg = a.size < b.size ? {a, b} : {b, a}
      !lg.starts_with?(sm) # E.g. Tpath[2] and Tpath[2—1] are incompatible.
    end

    private def compatible?(ref : Term, successor : Term, &predicate : Tpath -> Bool) : Bool
      compatible?(ref, successor, Tpath[], predicate)
    end

    private def compatible?(ref : Term, successor : Term, path, predicate) : Bool
      if ref == successor
        return true # compatible
      end

      unless (ref = ref.as_d?) && (successor = successor.as_d?)
        return predicate.call(path)
      end

      ref.each_entry do |key, value0|
        subpath = path.append(Tpath.value(key))
        unless value1 = successor[key]?
          # Successor removed *key*.
          return false unless predicate.call(subpath)
          next
        end

        # Successor possibly modified *key*.
        unless compatible?(value0, value1, subpath, predicate)
          return false
        end
      end

      successor.each_entry do |key, _|
        next if key.in?(ref)

        # Successor added *key*.
        subpath = path.append(Tpath.value(key))
        return false unless predicate.call(subpath)
      end

      true # compatible
    end

    private def compatible?(orig : Term, rep0 : Term, rep1 : Term) : Bool
      affected0 = Pf::Kit.stack_array(Tpath)

      _ = compatible?(orig, rep0) do |path|
        affected0 << path

        true # continue
      end

      compatible?(orig, rep1) do |path1|
        affected0.all? { |path0| compatible?(path0, path1) }
      end
    end

    # Accumulates changes made by *successor* into *acc*. Changes are found
    # by comparing *ref* and *successor*.
    #
    # WARNING: This method assumes implicitly that the changes of all *successors*
    # accumulated into *acc* are disjoint. If they conflict, this method will
    # break. You are expected to guard calls to this method with a disjointedness check.
    private def overlay(acc : Term, ref : Term, successor : Term) : Term
      unless (acc_dict = acc.as_d?) && (successor_dict = successor.as_d?)
        return successor
      end

      assert ref_dict = ref.as_d?

      result = acc_dict.transaction do |commit|
        ref_dict.each_entry do |key, ref_value|
          unless successor_value = successor_dict[key]?
            # Successor removed *key*.
            commit.without(key)
            next
          end

          # We'd like to keep acc's values unless the successor modifies
          # the entry.
          next if successor_value == ref_value

          # Successor modified *key*.
          commit.with(key, overlay(acc_dict[key], ref_value, successor_value))
        end

        successor.each_entry do |key, successor_value|
          next if key.in?(ref_dict)

          # Successor created *key*.
          commit.with(key, successor_value)
        end
      end

      Term.of(result)
    end

    def solve(hg : Hypergraph, &fn : MatchTable, Int32 -> Patch?) : Patch
      solns = Pf::Kit.stack_array(Soln)

      hg.each_node_with_head do |node, head|
        next unless queries = @queries[head]?

        queries.each do |query|
          maybe_matches = query.deps.all? do |_, dep|
            dep.min.zero? || hg.has_head?(dep.head)
          end

          next unless maybe_matches

          crawl(hg, node, query) do |match_table|
            solns << Soln.new(match_table, query, query.index)
          end
        end
      end

      if solns.empty?
        return Patch.new
      end

      # TODO: In the future we'll have long computations emit a Sync::Future or
      # something along those lines (pun not intended!) This would move them onto
      # another fiber, and we'll be able to process more solutions concurrently
      # in the meantime. This is where the "scheduler" should go.
      proposals = solns.compact_map do |soln|
        next unless proposal = fn.call(soln.match_table, soln.query_index)

        assert proposal.size <= soln.degree,
          "size of proposal exceeds the number of node participants \
           (#{proposal.size} > #{soln.degree} participants)"

        {soln, proposal.as(Patch)} # (cast, otherwise Crystal crashes with a compiler bug!)
      end

      merge(hg, proposals)
    end

    private def merge(hg : Hypergraph, proposals : Array({Soln, Patch})) : Patch
      if proposals.empty?
        return Patch.new
      end

      proposals.sort_by! { |soln, _| soln }

      # A table from node id to replacement proposals for that node along
      # with proposal index (used for ranking).
      #
      # NOTE: Proposals are sorted by soln, and iteration is inorder, thus
      # the arrays here are sorted as well by proposal index, asc, and
      # therefore by soln, asc.
      patchtab = {} of NodeId => Array({Term, UInt32})

      probably_conflicts = false

      proposals.each_with_index do |(_, proposal), proposal_index|
        proposal.each do |node_id, rep|
          reps = patchtab.put_if_absent(node_id) { [] of {Term, UInt32} }
          reps << {rep, proposal_index.to_u32}

          if reps.size > 1
            probably_conflicts = true
          end
        end
      end

      proposals_declined = Pf::USet32[]
      if probably_conflicts
        proposals_declined = decline_set(hg, patchtab)
      end

      Patch.transaction do |patch|
        patchtab.each do |node_id, reps|
          ref = hg[node_id]
          acc = ref

          reps.each do |rep, proposal_index|
            next if proposal_index.in?(proposals_declined)

            acc = overlay(acc, ref, rep)
          end

          patch.assoc(node_id, acc)
        end
      end
    end

    # Computes the proposal decline set for *patchtab*: declines proposals
    # that conflict.
    private def decline_set(hg : Hypergraph, patchtab : Hash(NodeId, Array({Term, UInt32}))) : Pf::USet32
      Pf::USet32.transaction do |declined|
        patchtab.each do |node_id, reps|
          orig = hg[node_id]

          reps.each_with_index do |(rep0, proposal_index0), i|
            next if proposal_index0.in?(declined)

            abstains = false

            reps.each_with_index do |(rep1, proposal_index1), j|
              next if i == j
              next if proposal_index1.in?(declined)

              # If our (rep0's) proposal index is smaller, then we are more preferred,
              # and thus we won't disable ourselves in case of conflict with rep1. This
              # means there is little point in checking for conflict in the first place.
              # rep1, who is less preferred, will do that instead.
              next if proposal_index0 < proposal_index1

              # We shouldn't have the same rule propose two versions for the same node.
              # This can't happen because all rules return a Patch, which is a hash table;
              # its keys cannot repeat.
              assert proposal_index0 != proposal_index1

              next if compatible?(orig, rep0, rep1)

              # We (rep0) are less preferred than rep1 and are also incompatible with
              # it. We are in conflict with rep1. We must abstain in favor of rep1
              # because we are less preferred.
              abstains = true
              break
            end

            next unless abstains

            declined << proposal_index0
          end
        end
      end
    end
  end
end
