module Ww::D7
  # This is usually generated by `D7.case`. `QueryIR` is later transformed to
  # `Regime::Query` which is much less pleasant to construct by hand.
  defrecord QueryIR,
    name : Term,
    pattern : Term,
    deps : Slice({Regime::Link, DepIR})

  struct QueryIR
    # Parses *term*, which should be a valid query DSL expression. Raises
    # `ArgumentError` if *term* is malformed.
    #
    # See `D7.case` for DSL docs.
    def self.parse(term : Term) : QueryIR
      Term.matchp(term, <<-WWML) do |query, name, deps|
      (query_ name_
       (%many deps_ min: 0
         -> link_ pattern_ {¦ name_
                              min_: (%optional 1 (%number +i32))
                              max_: (%optional 1 (%any° ∞ (%number +i32)))}))
      WWML
        dep_irs = deps.items.to_readonly_slice do |dep|
          link = Term.case(dep[:link]) do
            matchpi %{(one capture_)} do
              Regime::LinkOne.new(capture)
            end

            matchpi %{(many capture_ dep-capture_)} do
              Regime::LinkMany.new(capture, dep_capture)
            end
          end

          min = dep[:min].to(Int32)
          max = dep[:max] == Term.of(:∞) ? Int32::MAX : dep[:max].to(Int32)

          {link, DepIR.new(dep[:name], dep[:pattern], min, max)}
        end

        QueryIR.new(name, query, dep_irs)
      end
    end
  end

  # See `QueryIR`.
  defrecord DepIR,
    name : Term,
    pattern : Term,
    min : Int32,
    max : Int32

  class Regime
    defcase Query,
      name : Term,
      demands : Pf::USet32,
      pattern_id : UInt32,
      specificity : M1::Specificity,
      deps : Slice({Link, Dep})

    defrecord Dep,
      name : Term,
      pattern_id : UInt32,
      min : Int32,
      max : Int32

    alias Link = LinkOne | LinkMany

    defrecord LinkOne, capture : Term
    defrecord LinkMany, capture : Term, dep_capture : Term

    defrecord Pattern, op : M1::Op::Any, head : Term

    # :nodoc:
    def initialize(@patterns : Slice(Pattern), @queries : Slice(Query))
    end

    # Constructs a regime from the given list of query IR objects.
    def self.new(query_irs : Indexable(QueryIR)) : Regime
      patterns = Pf::Kit.stack_array(Pattern)

      queries = query_irs.to_readonly_slice do |query_ir|
        demands = Pf::USet32[]

        query_pattern_id = patterns.size.to_u32
        query_normp = M1.normal(query_ir.pattern)
        query_pattern = M1.operator(query_normp)
        query_specificity = M1.specificity(query_normp)
        query_head = M1.head?(query_normp)
        assert query_head, "Could not determine query pattern's head: #{query_ir.pattern}"

        patterns << Pattern.new(query_pattern, query_head)
        demands = demands.add(query_pattern_id)

        deps = query_ir.deps.to_readonly_slice do |(link, dep_ir)|
          dep_pattern_id = patterns.size.to_u32
          dep_normp = M1.normal(dep_ir.pattern)
          dep_pattern = M1.operator(dep_normp)
          dep_head = M1.head?(dep_normp)
          assert dep_head, "Could not determine dependency's head: #{dep_ir.pattern}"

          patterns << Pattern.new(dep_pattern, dep_head)
          if dep_ir.min > 0
            demands = demands.add(dep_pattern_id)
          end

          {link, Dep.new(dep_ir.name, dep_pattern_id, dep_ir.min, dep_ir.max)}
        end

        Query.new(query_ir.name, demands, query_pattern_id, query_specificity, deps)
      end

      new(patterns.to_readonly_slice(&.itself), queries)
    end

    # *Perception* is the first step: the "sensory heads" of rules look at
    # the hypergraph and trigger, or don't. The result is a map of node
    # ids to bit sets of rules they excite -- the *excitation map*.
    #
    # NOTE: At this point, rules are allowed to misfire: false positives are
    # allowed (rule fires when it shouldn't); but false negatives are not.
    private def perceive(hg : Hypergraph) : Hash(NodeId, Pf::USet32)
      excitations = {} of NodeId => Pf::USet32

      hg.each_node do |node|
        @patterns.each_with_index do |pattern, index|
          next unless M1.probably_matches?(pattern.op, node.term)

          pattern_id = index.to_u32

          excites0 = excitations[node.id]? || Pf::USet32[]
          excites1 = excites0.add(pattern_id)

          excitations[node.id] = excites1
        end
      end

      excitations
    end

    # From the excitation map, we compute a *supply* bit set. It tells us which
    # rules are "supplied" in the hypergraph (but remember, perception is
    # imprecise -- it may give us false positives).
    private def supply(excitations)
      excitations.reduce(Pf::USet32[]) do |supply, (_, excites)|
        supply | excites
      end
    end

    private def excites?(excitations, pattern_id : UInt32, node : Node) : Bool
      unless excites = excitations[node.id]?
        return false
      end

      excites.includes?(pattern_id)
    end

    private def match?(env : Term::Dict, pattern_id : UInt32, candidate : Node) : Term::Dict?
      pattern = @patterns[pattern_id]

      M1.match?(env, pattern.op, candidate.term)
    end

    private def fanout(env : Term::Dict, link : LinkOne) : Indexable({Term, Term})
      unless edge = env[link.capture]?
        raise KeyError.new("capture `#{link.capture}` not found")
      end

      {% unless flag?(:release) %}
        assert Term.edge?(edge)
      {% end %}

      { {link.capture, edge} }
    end

    private def fanout(env : Term::Dict, link : LinkMany) : Indexable({Term, Term})
      unless edges = env[link.capture]?
        raise KeyError.new("capture `#{link.capture}` not found")
      end

      {% unless flag?(:release) %}
        assert edges.items.all? { |edge| Term.edge?(edge) }
      {% end %}

      edges.items.to_readonly_slice { |edge| {link.dep_capture, edge} }
    end

    private def crawl(hg, excitations, node : Node, query : Query, & : MatchTable ->)
      return unless excites?(excitations, query.pattern_id, node)
      return unless query_env = match?(Term[], query.pattern_id, node)

      seen = Pf::USet32[node.id]
      match_table = MatchTable.assoc(query.name, MatchGroup[Match.new(node, query_env)])

      query.deps.each do |link, dep|
        fanout = fanout(query_env, link)
        if fanout.empty?
          # (qux ⏏us⏏←((%past @_ min: 0))) foo
          #   -> (many ⏏us⏏ u) (cell @u_) {name: bar, min: 0, max: 0}
          #
          # Here, `us` could be empty. This is a perfectly legitimate kind of rule,
          # so we must handle it properly.
          assert !dep.name.in?(match_table)
          match_table = match_table.assoc(dep.name, MatchGroup.empty)
          next
        end

        fanout.each do |link_unit, link_edge|
          neighbors = Pf::Kit.stack_array(Node)

          hg.each_edge(node.id) do |edge|
            # edge : Hyperedge
            next unless link_edge == edge.term

            hg.each_member(edge) do |neighbor|
              next if neighbor.id.in?(seen) # Don't allow to depend on the same node twice.
              next unless excites?(excitations, dep.pattern_id, neighbor)

              neighbors << neighbor
            end

            break
          end

          return if neighbors.size < dep.min

          matches = Pf::Kit.stack_array(Match)

          # Since dep patterns are "free-floating" with respect to the query
          # pattern, we can't rely on M1 constraints and must instead provide
          # an environment relating everything manually. Here, e.g., for @a:
          #
          # (qux @⏏a_⏏ @b_) foo
          #   -> (one ⏏a⏏) (cell @⏏a_⏏ x_) {name: bar}
          #   -> (one b) (cell @b_ y_) {name: baz}
          dep_constraint = Term[].with(link_unit, link_edge)

          neighbors.each do |neighbor|
            next unless dep_env = match?(dep_constraint, dep.pattern_id, neighbor)

            matches << Match.new(neighbor, dep_env)
          end

          return unless dep.min <= matches.size <= dep.max

          matches.each do |match|
            seen = seen.add(match.node.id)
          end

          match_group0 = match_table[dep.name]? || MatchGroup.empty
          match_group1 = match_group0.append_many(matches, &.itself)
          match_table = match_table.assoc(dep.name, match_group1)
        end
      end

      assert match_table.size == 1 + query.deps.size

      # Make sure that edges in dependencies agree with the query env.
      #
      #   (qux @a_ @b_ @c_) qux
      #     -> (one a) (foo @a_ ⏏@b_⏏) {name: foo}
      #     -> (one b) (bar @b_ ⏏@c_⏏) {name: bar}
      #     -> (one c) (baz @c_ ⏏@a_⏏) {name: baz}
      #
      # Here, the highlighted edges must be in agreement with the query env.
      #
      # We do not enforce agreement among dependencies *for captures absent in
      # the master env*. For example, in:
      #
      #   (qux @a_ @b_) qux
      #     -> (one a) (foo @a_ term_) {name: foo}
      #     -> (one b) (bar @b_ term_) {name: bar}
      #
      # ... both *term*s are matched independently.
      query.deps.each do |_, dep|
        filtered = Pf::Kit.stack_array(Match, 8)

        match_group = match_table[dep.name]
        match_group.each do |match|
          next unless query_env.agrees_with?(match.env)
          filtered << match
        end

        next if match_group.size == filtered.size
        return unless dep.min <= filtered.size <= dep.max

        match_table = match_table.assoc(dep.name, filtered.to_readonly_slice(&.itself))
      end

      assert match_table.size == 1 + query.deps.size

      yield match_table
    end

    private def crawl(hg : Hypergraph, excitations, candidates, &)
      hg.each_node do |node|
        candidates.each do |query, query_index|
          crawl(hg, excitations, node, query) do |match_table|
            yield match_table, query_index
          end
        end
      end
    end

    # :nodoc:
    #
    # Represents a solution.
    defcase Soln, match_table : MatchTable, query : Query, query_index : Int32 do
      @degree = Int32::MAX

      def degree : Int32
        if @degree == Int32::MAX
          @degree = match_table.sum(&.size)
        end

        assert 0 <= @degree < Int32::MAX

        @degree
      end

      @participants : Slice(Term)?

      def participants : Slice(Term)
        @participants ||= begin
          participants = Pf::Kit.stack_array(Term, 8)

          match_table.each do |_, match_group|
            match_group.each do |match|
              participants << match.node.term
            end
          end

          participants.sort! { |a, b| Term.compare(a, b) }
          participants.to_readonly_slice(&.itself)
        end
      end

      # NOTE: the smallest rank is the most specific rank, it should be picked
      # the earliest.
      def <=>(other : Soln) : Int32?
        # Prefer higher degree.
        cmp = other.degree <=> degree
        return cmp unless cmp == 0 # equal

        # Prefer higher query specificity.
        cmp = other.query.specificity <=> query.specificity
        return cmp unless cmp == 0 # equal

        # Prefer solutions for rules lower down (programmers usually read "X
        # below Y" as "X overrides Y").
        cmp = query_index <=> other.query_index
        return unless cmp == 0 # equal

        # Prefer lexicographically smallest solutions.
        participants <=> other.participants
      end
    end

    private def compatible?(a : Tpath, b : Tpath) : Bool
      if a.size == b.size
        return a != b # if different, then they're compatible
      end

      short, long = {a, b}.minmax_by(&.size)
      !long.starts_with?(short) # E.g. Tpath[2] and Tpath[2—1] are incompatible.
    end

    private def compatible?(ref : Term, successor : Term, &predicate : Tpath -> Bool) : Bool
      compatible?(ref, successor, Tpath[], predicate)
    end

    private def compatible?(ref : Term, successor : Term, path, predicate) : Bool
      if ref == successor
        return true # compatible
      end

      unless (ref = ref.as_d?) && (successor = successor.as_d?)
        return predicate.call(path)
      end

      ref.each_entry do |key, value0|
        subpath = path.append(Tpath.value(key))
        unless value1 = successor[key]?
          # Successor removed *key*.
          return false unless predicate.call(subpath)
          next
        end

        # Successor possibly modified *key*.
        unless compatible?(value0, value1, subpath, predicate)
          return false
        end
      end

      successor.each_entry do |key, _|
        next if key.in?(ref)

        # Successor added *key*.
        subpath = path.append(Tpath.value(key))
        return false unless predicate.call(subpath)
      end

      true # compatible
    end

    private def compatible?(orig : Term, rep0 : Term, rep1 : Term) : Bool
      affected0 = Pf::Kit.stack_array(Tpath)

      _ = compatible?(orig, rep0) do |path|
        affected0 << path

        true # continue
      end

      compatible?(orig, rep1) do |path1|
        affected0.all? { |path0| compatible?(path0, path1) }
      end
    end

    # Accumulates changes made by *successor* into *acc*. Changes are found
    # by comparing *ref* and *successor*.
    #
    # WARNING: This method assumes implicitly that the changes of all *successors*
    # accumulated into *acc* are disjoint. If they conflict, this method will
    # break. You are expected to guard calls to this method with a disjointedness check.
    private def overlay(acc : Term, ref : Term, successor : Term) : Term
      unless (acc_dict = acc.as_d?) && (successor_dict = successor.as_d?)
        return successor
      end

      assert ref_dict = ref.as_d?

      result = acc_dict.transaction do |commit|
        ref_dict.each_entry do |key, ref_value|
          unless successor_value = successor_dict[key]?
            # Successor removed *key*.
            commit.without(key)
            next
          end

          # We'd like to keep acc's values unless the successor modifies
          # the entry.
          next if successor_value == ref_value

          # Successor modified *key*.
          commit.with(key, overlay(acc_dict[key], ref_value, successor_value))
        end

        successor.each_entry do |key, successor_value|
          next if key.in?(ref_dict)

          # Successor created *key*.
          commit.with(key, successor_value)
        end
      end

      Term.of(result)
    end

    def solve(hg : Hypergraph, & : MatchTable, Int32 -> Patch?) : Patch
      excitations = perceive(hg)
      supply = supply(excitations)

      # Since queries *demand* certain patterns, this lets us reject a great deal
      # of them before commencing more complex search.
      candidates = Pf::Kit.stack_array({Query, Int32})
      @queries.each_with_index do |query, query_index|
        next unless query.demands.subset_of?(supply)

        candidates << {query, query_index}
      end

      solns = [] of Soln

      # Next, we start `crawl`ing from each node.
      crawl(hg, excitations, candidates) do |match_table, query_index|
        solns << Soln.new(match_table, @queries[query_index], query_index)
      end

      # TODO: In the future we'll have long computations emit a Sync::Future or
      # something along those lines (pun not intended!) This would move them onto
      # another fiber, and we'll be able to process more solutions concurrently
      # in the meantime. This is where the "scheduler" should go.
      proposals = solns.compact_map do |soln|
        next unless proposal = yield soln.match_table, soln.query_index

        assert proposal.size <= soln.degree,
          "size of proposal exceeds the number of node participants \
           (#{proposal.size} > #{soln.degree} participants)"

        {soln, proposal.as(Patch)} # (cast, otherwise Crystal crashes with a compiler bug!)
      end

      merge(hg, proposals)
    end

    private def merge(hg : Hypergraph, proposals : Array({Soln, Patch})) : Patch
      if proposals.empty?
        return Patch.new
      end

      proposals.sort_by! { |soln, _| soln }

      # A table from node id to replacement proposals for that node along
      # with proposal index (used for ranking).
      #
      # NOTE: Proposals are sorted by soln, and iteration is inorder, thus
      # the arrays here are sorted as well by proposal index, asc, and
      # therefore by soln, asc.
      patchtab = {} of NodeId => Array({Term, UInt32})

      probably_conflicts = false

      proposals.each_with_index do |(_, proposal), proposal_index|
        proposal.each do |node_id, rep|
          reps = patchtab.put_if_absent(node_id) { [] of {Term, UInt32} }
          reps << {rep, proposal_index.to_u32}

          if reps.size > 1
            probably_conflicts = true
          end
        end
      end

      proposals_declined = Pf::USet32[]
      if probably_conflicts
        proposals_declined = decline_set(hg, patchtab)
      end

      Patch.transaction do |patch|
        patchtab.each do |node_id, reps|
          ref = hg[node_id]
          acc = ref

          reps.each do |rep, proposal_index|
            next if proposal_index.in?(proposals_declined)

            acc = overlay(acc, ref, rep)
          end

          patch.assoc(node_id, acc)
        end
      end
    end

    # Computes the proposal decline set for *patchtab*: declines proposals
    # that conflict.
    private def decline_set(hg : Hypergraph, patchtab : Hash(NodeId, Array({Term, UInt32}))) : Pf::USet32
      Pf::USet32.transaction do |declined|
        patchtab.each do |node_id, reps|
          orig = hg[node_id]

          reps.each_with_index do |(rep0, proposal_index0), i|
            next if proposal_index0.in?(declined)

            fits = true

            reps.each_with_index do |(rep1, proposal_index1), j|
              next if i == j
              next if proposal_index1.in?(declined)

              # If we (rep0) are less disliked than rep1, we won't disable ourselves
              # in case of conflict. Thus there is little point in finding a conflict.
              #
              # If our (rep0's) proposal index is smaller, then we are more preferred,
              # and thus we won't disable ourselves in case of conflict with rep1. This
              # means there is little point in checking for conflict in the first place.
              # rep1, who is less preferred, will do that instead.
              next if proposal_index0 < proposal_index1

              # We shouldn't have the same rule propose two versions for the same node.
              # This can't happen because all rules return a Patch.
              assert proposal_index0 != proposal_index1

              next if compatible?(orig, rep0, rep1)

              # We (rep0) are less preferred than rep1 and are also incompatible with
              # with it. We are in conflict with rep1. We must abstain because we are
              # less preferred.
              fits = false
              break
            end

            next if fits

            declined << proposal_index0
          end
        end
      end
    end
  end
end
