module Ww::Soma::DwUIR
  # A layer should be imagined simply as a 2D array of `Pixel`s.
  #
  # Note that the pixels are stored in compressed form; run length encoding
  # is used, as it works very well for visual & composition use cases and comes
  # with very low overhead for the memory savings that it generates.
  #
  # To save memory on very short runs of pixels (runs of 1-5 pixels), we are
  # taking away five sentinel alpha values (see the `SENTINEL_` constants). If
  # the user's alpha is one of these sentinel values, we increment it by one.
  # Such a small change is not expected to be perceptible by the user; serving
  # as the main motivation for this minor optimization.
  #
  # TODO: I think compression here was a very very bad design choice and we're
  # partly suffering from it in terms of performance!!! I am very unexperienced
  # in these things!!
  # Memory is cheap, and we can represent regions with solid fills with Tiles to avoid the overhead
  # of RLE pack/unpack in the hot path while having fast SIMD interior blending loops!!!
  # Each tile should be: Empty, Solid (just one pixel), NonSolid (AoS premultiplied u8 r,g,b,a).
  # Then use SIMD to blend the latter two over a pixel rect: Solid is "fill", NonSolid is "blend-over".
  class Layer
    # Returns the width of this layer.
    getter width : Int32

    # Returns the height of this layer.
    getter height : Int32

    # NOTE: the sentinel values were generated by a PRNG; there is nothing
    # special about them, other than that they must not be each other's
    # successors.

    SENTINEL0 =  19u32
    SENTINEL1 =  64u32
    SENTINEL2 =  78u32
    SENTINEL3 = 136u32
    SENTINEL4 = 239u32

    # Constructs a `Layer` of the given *width* and *height*.
    #
    # - *pixels* gives the byte array of pixels.
    # - *stride* specifies the byte size of one row of pixels in *pixels*.
    #
    # NOTE: it is your responsibility to ensure the format of *pixels* conforms
    # to the one used by `Pixel`. If the formats differ, you'll get wrong colors
    # and invalid blending behavior.
    #
    # NOTE: *pixels* are reinterpreted as `UInt32` without any further bit rearrangement.
    # It is your responsibility to make sure that simply reinterpreting *pixels* as
    # UInt32 is enough to convert them to `Pixel`s. This usually means premultiplied BGRA,
    # since we assume Wirewright only runs on little-endian machines.
    def initialize(pixels : UInt8*, @width, @height, stride : Int32)
      @data = [] of UInt32

      raw = pixels.to_slice(@height * stride)

      Layer.pack(raw) do |count, pixel|
        alpha = pixel >> 24

        if alpha == 255u32
          case count
          when 1
            @data << ((pixel & 0x00ffffff) | (SENTINEL0 << 24))
            next
          when 2
            @data << ((pixel & 0x00ffffff) | (SENTINEL1 << 24))
            next
          when 3
            @data << ((pixel & 0x00ffffff) | (SENTINEL2 << 24))
            next
          when 4
            @data << ((pixel & 0x00ffffff) | (SENTINEL3 << 24))
            next
          when 5
            @data << ((pixel & 0x00ffffff) | (SENTINEL4 << 24))
            next
          end
        elsif alpha > 0u32 && alpha.in?(SENTINEL0, SENTINEL1, SENTINEL2, SENTINEL3, SENTINEL4)
          alpha += 1
          pixel = (pixel & 0x00ffffff) | (alpha << 24)
        end

        @data << pixel << count
      end
    end

    # :nodoc:
    def self.pack(pixels : Slice(UInt8), & : UInt32, UInt32 ->) : Nil
      state = nil
      count = 0u32

      each_u32_pixel(pixels) do |pixel|
        if state
          if state == pixel
            count += 1
            next
          end

          yield count, state
        end

        state = pixel
        count = 1u32
      end

      if state
        yield count, state
      end
    end

    # :nodoc:
    def self.each_u32_pixel(pixels : Slice(UInt8), & : UInt32 ->)
      # This feels really really really wonky due to the dependence on system-
      # endianness; but we use it in places where that's more or less expected
      # behavior. PlutoVG does this; and Wirewright is only ever expected to
      # be run on little-endian machines.
      pixels.unsafe_slice_of(UInt32).each do |pixel|
        yield pixel
      end
    end

    # Yields each pixel followed by its coordinates.
    def each_pixel_with_coords(& : Pixel, Int32, Int32 ->) : Nil
      x = y = 0
      cursor = 0
      offset = 0

      while cursor < @data.size
        pixel = @data[cursor]

        # Do not process runs of transparent pixels.
        if pixel == 0u32
          count = @data[cursor + 1]
          offset += count
          y, x = offset.divmod(@width)
          cursor += 2
          next
        end

        # If pixel's alpha is one of sentinel values, interpret it as count
        # and set alpha = 255.
        count, bits_to_set, step =
          case pixel >> 24
          when SENTINEL0 then {1, 0xff000000u32, 1}
          when SENTINEL1 then {2, 0xff000000u32, 1}
          when SENTINEL2 then {3, 0xff000000u32, 1}
          when SENTINEL3 then {4, 0xff000000u32, 1}
          when SENTINEL4 then {5, 0xff000000u32, 1}
          else
            {@data[cursor + 1], 0u32, 2}
          end

        pixel |= bits_to_set

        count.times do
          yield Pixel.new(pixel), x, y

          if x + 1 < width
            x += 1
          else
            x = 0
            y += 1
          end
        end

        offset += count
        cursor += step
      end
    end

    # Returns the full byte size of this layer assuming no compression.
    #
    # Use `bytesize` to get the compressed in-memory size.
    def fullsize : Int32
      @width * @height * 4
    end

    # Returns the compressed in-memory byte size of this layer. This is
    # the real no. of bytes that this layer occupies in memory. Note that
    # control structures are not included in the returned bytesize.
    def bytesize : Int32
      @data.size * 4
    end

    def inspect(io)
      io << "Layer(" << width << "x" << height << ", size="
      fullsize.humanize_bytes(io)
      io << "->"
      bytesize.humanize_bytes(io)
      io << ")"
    end
  end
end
